"""add rating column to products

Revision ID: 13661d793c95
Revises: 86245f90016b
Create Date: 2026-04-21 20:03:27.434423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13661d793c95'
down_revision: Union[str, Sequence[str], None] = '86245f90016b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.alter_column('products', 'product_img',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_img',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
