"""add new columns to products

Revision ID: d0211f50b273
Revises: 13661d793c95
Create Date: 2026-04-24 17:15:07.140034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0211f50b273'
down_revision: Union[str, Sequence[str], None] = '13661d793c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True ,server_default='0'))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('discount_percentage', sa.Integer(), nullable=True ,server_default='0'))
    op.add_column('products', sa.Column('product_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_images')
    op.drop_column('products', 'discount_percentage')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
