"""add is_active column

Revision ID: d2454f487cef
Revises: 
Create Date: 2026-04-17 15:07:55.980210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2454f487cef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items',sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('carts',sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('carts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_active')
    op.drop_column('orders', 'is_active')
    op.drop_column('order_items', 'created_at')
    op.drop_column('order_items', 'is_active')
    op.drop_column('carts', 'created_at')
    op.drop_column('carts', 'is_active')
    op.drop_column('cart_items', 'created_at')
    op.drop_column('cart_items', 'is_active')
    # ### end Alembic commands ###
